name: build
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        build_type: [Release]
        enable_ui: [on]
    steps:
    - name: get aseprite
      shell: zsh {0}
      run: |
        mkdir Aseprite
        cd Aseprite
        curl -LJO https://github.com/aseprite/aseprite/releases/download/v1.2.40/Aseprite-v1.2.40-Source.zip
        unzip Aseprite-v1.2.40-Source.zip
        cd ..
        mkdir Skia
        cd Skia
        curl -LJO https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-macOS-Release-x64.zip
        unzip Skia-macOS-Release-x64.zip
        cd ..
        cd Aseprite
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      if: runner.os == 'Linux'
      with:
        key: ${{ matrix.os }}-${{ matrix.enable_ui }}
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Workaround for windows-2022 and cmake 3.25.0
      if: runner.os == 'Windows'
      shell: bash
      run: rm -rf C:/Strawberry/
    - name: Install Dependencies
      shell: zsh {0}
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          sudo apt-get update -qq
          sudo apt-get install -y \
            libx11-dev libxcursor-dev libxi-dev
        fi
    - name: Generating Makefiles
      shell: zsh {0}
      run: |
        cd Aseprite
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          export enable_ccache=off
        else
          export enable_ccache=on
        fi
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_TESTS=OFF \
          -DENABLE_UI=${{ matrix.enable_ui }} \
          -DENABLE_CCACHE=$enable_ccache \
          -DCMAKE_OSX_ARCHITECTURES=x86_64 \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$(PWD)/../Skia \
          -DSKIA_LIBRARY_DIR=$(PWD)/../Skia/out/Release-x64 \
          -DSKIA_LIBRARY=$(PWD)/../Skia/out/Release-x64/libskia.a \
          -DCMAKE_INSTALL_PREFIX=$(PWD)/install \
          -G Ninja
    - name: Compiling
      shell: zsh {0}
      run: |
        cd Aseprite/build && ninja
    - name: installing
      shell: zsh {0}
      run: |
        alias sh=zsh
        cd Aseprite/build && ninja install
        cd ..
        tar -czvf output.tar.gz install
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Aseprite/output.tar.gz
        
    - name: See output
      shell: zsh {0}
      run: |
        cd Aseprite
        ls -R
